In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from feature_genarator import *
from sklearn.metrics import accuracy_score,roc_auc_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import make_scorer
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
from scipy.io import loadmat
from iFeature.codes import *

In [14]:
# pos = 'datas/AIP/Ind-positive.txt'
# neg = 'datas/AIP/Ind-negative.txt'


In [15]:
from iFeature.codes.AAC import AAC
def aac(input):
    a = input.rstrip('txt')
    out = a + 'aac.csv'
    df_out = AAC(input)
    df_in = pd.read_csv(out)
    return df_in

aac('datas/AIP/Ind-negative.txt')

KeyError: 'order'

In [16]:
pos.keys()

NameError: name 'pos' is not defined

In [71]:
data2 = loadmat('data_test/Pse pssm.mat')

In [72]:
data2.keys()
# data2.shape
# data2.head()

dict_keys(['__header__', '__version__', '__globals__', 'feature'])

In [73]:
data2['feature']

array([[ 0.3573961 ,  0.18508732,  0.26064983, ..., -0.        ,
        -0.        , -0.        ],
       [ 0.40848067,  0.2814922 ,  0.34532204, ..., -0.        ,
        -0.        , -0.        ],
       [ 0.1996597 ,  0.30070361,  0.1996597 , ..., -0.        ,
        -0.        , -0.        ],
       ...,
       [ 0.41914162,  0.30404848,  0.38544056, ..., -0.        ,
        -0.        , -0.        ],
       [ 0.30461034,  0.2756512 ,  0.2756512 , ..., -0.        ,
        -0.        , -0.        ],
       [ 0.3009676 ,  0.26109138,  0.34602386, ..., -0.        ,
        -0.        , -0.        ]], dtype=float32)

In [78]:
y = [data2['feature']==0]

In [80]:
print(sum(y))

[[0 0 0 ... 1 1 1]
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 1 1 1]
 ...
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 1 1 1]]


In [33]:
data2 = loadmat('data_test/all_whsx_list.mat')

In [34]:
print(data2)

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Fri Apr 13 21:09:59 2018', '__version__': '1.0', '__globals__': [], 'all_whsx': array([[array(['89.000'], dtype='<U6'), array(['174.000'], dtype='<U7'),
        array(['132.000'], dtype='<U7'), ...,
        array(['204.000'], dtype='<U7'), array(['181.000'], dtype='<U7'),
        array(['117.000'], dtype='<U7')],
       [array(['4.000'], dtype='<U5'), array(['6.000'], dtype='<U5'),
        array(['2.000'], dtype='<U5'), ...,
        array(['1.000'], dtype='<U5'), array(['2.000'], dtype='<U5'),
        array(['4.000'], dtype='<U5')],
       [array(['11.500'], dtype='<U6'), array(['14.280'], dtype='<U6'),
        array(['12.820'], dtype='<U6'), ...,
        array(['21.670'], dtype='<U6'), array(['18.030'], dtype='<U6'),
        array(['21.570'], dtype='<U6')],
       ...,
       [array(['8.300'], dtype='<U5'), array(['5.700'], dtype='<U5'),
        array(['4.400'], dtype='<U5'), ...,
        array(['1.300'], dtype='<U5'

In [35]:
data2.keys()

dict_keys(['__header__', '__version__', '__globals__', 'all_whsx'])

In [52]:
print(f)

['H ANDN920101\n', 'D alpha-CH chemical shifts (Andersen et al., 1992)\n', 'R PMID:1575719\n', 'A Andersen, N.H., Cao, B. and Chen, C.\n', 'T Peptide/protein structure analysis using the chemical shift index method: \n', '  upfield alpha-CH values reveal dynamic helices and aL sites\n', 'J Biochem. and Biophys. Res. Comm. 184, 1008-1014 (1992)\n', 'C BUNA790102    0.949\n', 'I    A/L     R/K     N/M     D/F     C/P     Q/S     E/T     G/W     H/Y     I/V\n', '    4.35    4.38    4.75    4.76    4.65    4.37    4.29    3.97    4.63    3.95\n', '    4.17    4.36    4.52    4.66    4.44    4.50    4.35    4.70    4.60    3.95\n', '//\n', 'H ARGP820101\n', 'D Hydrophobicity index (Argos et al., 1982)\n', 'R PMID:7151796\n', 'A Argos, P., Rao, J.K.M. and Hargrave, P.A.\n', 'T Structural prediction of membrane-bound proteins\n', 'J Eur. J. Biochem. 128, 565-575 (1982)\n', 'C JOND750101    1.000  SIMZ760101    0.967  GOLD730101    0.936\n', '  TAKK010101    0.906  MEEJ810101    0.891  ROSM880

In [70]:
print(f[0])

H ANDN920101



In [112]:
t=open('data_test/dwnld_table.txt', 'r').readlines()

In [113]:
print(t[8])

1ab9D	TPGVY	-0.704371	Negative



In [115]:
t = pd.read_csv('data_test/dwnld_table.csv')

In [116]:
print(t)
t.keys()

    Seq.ID Epitope     Score Prediction
0      NaN     NaN       NaN        NaN
1    1ab9D   TPGVY -0.704371   Negative
2    1bfzA   SYVKA -0.704371   Negative
3    1elrB   MEEVD -0.704371   Negative
4    1gybE   GFSFG -0.704371   Negative
..     ...     ...       ...        ...
96   3ddaB  QRATKM -0.704371   Negative
97   3ddbB  RRATKM -0.704371   Negative
98   3driB  AASASA -0.704371   Negative
99   3fvaA  NNQNTF -0.704371   Negative
100  3idgC  ALDKWD -0.704371   Negative

[101 rows x 4 columns]


Index(['Seq.ID', 'Epitope', 'Score', 'Prediction'], dtype='object')

In [117]:
print(t['Prediction'])

0           NaN
1      Negative
2      Negative
3      Negative
4      Negative
         ...   
96     Negative
97     Negative
98     Negative
99     Negative
100    Negative
Name: Prediction, Length: 101, dtype: object


In [140]:
pos=open('original/pos_training.txt', 'r').readlines()
print(pos[0])

In [135]:
pos = 'original/pos_training.txt'
neg = 'original/neg_training.txt'
import tqdm
from iFeature.codes import AAC

In [136]:
# Amino acid composition (AAC)

from Pfeature.Pfeature.Pfeature.pfeature import aac_wp

def aac(input):
  a = input.rstrip('txt')
  output = a + 'aac.csv'
  df_out = aac_wp(input, output)
  df_in = pd.read_csv(output)
  return df_in

aac('original/pos_training.txt')



TypeError: 'float' object is not iterable

In [137]:

def feature_calc(po, ne, feature_name):
  # Calculate feature
  po_feature = feature_name(po)
  ne_feature = feature_name(ne)
  # Create class labels
  po_class = pd.Series(['positive' for i in range(len(po_feature))])
  ne_class = pd.Series(['negative' for i in range(len(ne_feature))])
  # Combine po and ne
  po_ne_class = pd.concat([po_class, ne_class], axis=0)
  po_ne_class.name = 'class'
  po_ne_feature = pd.concat([po_feature, ne_feature], axis=0)
  # Combine feature and class
  df = pd.concat([po_ne_feature, po_ne_class], axis=1)
  return df

feature = feature_calc(pos, neg, aac) # AAC
#feature = feature_calc(pos, neg, dpc) # DPC
feature

TypeError: 'float' object is not iterable

In [145]:
pos=open('original/pos_training.txt', 'r').readlines()
pos.keys()

AttributeError: 'list' object has no attribute 'keys'